name: Feature request
description: Propón una mejora funcional o técnica
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema a resolver
      description: Qué fricción actual resuelve esta propuesta
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Propuesta
      description: Describe alcance funcional y técnico
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impacto esperado
      description: Conversión, retención, performance, mantenimiento, etc.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación
      placeholder: |
        - [ ] Criterio 1
        - [ ] Criterio 2
    validations:
      required: true
