export const CALCULATOR_CATEGORIES = [
  "todas",
  "renta",
  "iva",
  "laboral",
  "patrimonio",
  "sanciones",
  "otros",
] as const;

export type CalculatorCategory = (typeof CALCULATOR_CATEGORIES)[number];

export type CalculatorBadge = "Actualizado 2026" | "Incluye reforma" | "Nuevo";

export interface CalculatorCatalogItem {
  id: string;
  href: string;
  title: string;
  description: string;
  iconName: string;
  articles: string[];
  category: Exclude<CalculatorCategory, "todas">;
  tags: string[];
  intents: string[];
  badges: CalculatorBadge[];
  related: string[];
  isTop5?: boolean;
}

export const CALCULATORS_CATALOG: CalculatorCatalogItem[] = [
  {
    id: "uvt",
    href: "/calculadoras/uvt",
    title: "Conversor UVT ↔ COP",
    description: "Convierte entre UVT y pesos colombianos. Historico 2006-2026.",
    iconName: "ArrowLeftRight",
    articles: ["868"],
    category: "otros",
    tags: ["uvt", "conversion", "pesos", "tabla"],
    intents: ["convertir uvt", "valor uvt", "pasar a pesos"],
    badges: ["Actualizado 2026"],
    related: ["renta", "retencion", "debo-declarar"],
  },
  {
    id: "retencion",
    href: "/calculadoras/retencion",
    title: "Retencion en la Fuente",
    description: "Calcula retencion por concepto, monto y tabla progresiva de salarios.",
    iconName: "Receipt",
    articles: ["392", "401", "383"],
    category: "renta",
    tags: ["retencion", "retefuente", "rete", "honorarios", "servicios", "salarios"],
    intents: ["calcular retencion", "cuanto me retienen", "retencion en la fuente"],
    badges: ["Actualizado 2026", "Incluye reforma"],
    related: ["retencion-salarios", "renta", "comparador"],
    isTop5: true,
  },
  {
    id: "renta",
    href: "/calculadoras/renta",
    title: "Renta Personas Naturales",
    description: "Impuesto de renta con desglose marginal segun Art. 241 ET.",
    iconName: "Landmark",
    articles: ["241", "206", "336"],
    category: "renta",
    tags: ["renta", "impuesto", "persona natural", "declaracion"],
    intents: ["cuanto pago de renta", "impuesto de renta", "declarar renta persona natural"],
    badges: ["Actualizado 2026", "Incluye reforma"],
    related: ["debo-declarar", "retencion", "anticipo"],
    isTop5: true,
  },
  {
    id: "sanciones",
    href: "/calculadoras/sanciones",
    title: "Sancion por Extemporaneidad",
    description: "Calcula sancion por presentacion extemporanea con reducciones Art. 640.",
    iconName: "AlertTriangle",
    articles: ["641", "642", "640"],
    category: "sanciones",
    tags: ["sancion", "extemporaneidad", "declaracion tardia"],
    intents: ["sancion extemporaneidad", "multa por declarar tarde"],
    badges: ["Actualizado 2026"],
    related: ["sanciones-ampliadas", "intereses-mora"],
  },
  {
    id: "gmf",
    href: "/calculadoras/gmf",
    title: "GMF (4x1000)",
    description: "Gravamen a movimientos financieros con calculo de exencion 350 UVT.",
    iconName: "Banknote",
    articles: ["871", "879"],
    category: "otros",
    tags: ["gmf", "4x1000", "banco"],
    intents: ["calcular 4x1000", "gmf"],
    badges: ["Actualizado 2026"],
    related: ["uvt", "retencion"],
  },
  {
    id: "iva",
    href: "/calculadoras/iva",
    title: "Referencia IVA",
    description: "Calcula y extrae IVA 19% y 5%. Referencia rapida exento vs excluido.",
    iconName: "ShoppingCart",
    articles: ["468", "477", "424"],
    category: "iva",
    tags: ["iva", "impuesto ventas", "extraer iva"],
    intents: ["calcular iva", "sumar iva", "sacar iva"],
    badges: ["Actualizado 2026"],
    related: ["consumo", "ica", "retencion"],
  },
  {
    id: "comparador",
    href: "/calculadoras/comparador",
    title: "Comparador de Contratacion",
    description: "Compara laboral, salario integral y servicios para empresa y trabajador.",
    iconName: "Users",
    articles: ["383", "241", "905"],
    category: "laboral",
    tags: ["contratacion", "laboral", "integral", "independiente", "servicios"],
    intents: ["que tipo de contrato me conviene", "comparar contratacion", "laboral vs servicios"],
    badges: ["Actualizado 2026", "Incluye reforma"],
    related: ["nomina-completa", "seguridad-social", "retencion"],
    isTop5: true,
  },
  {
    id: "seguridad-social",
    href: "/calculadoras/seguridad-social",
    title: "Aportes a Seguridad Social",
    description: "Calcula aportes a salud, pension, ARL y parafiscales.",
    iconName: "Shield",
    articles: ["204"],
    category: "laboral",
    tags: ["seguridad social", "salud", "pension", "arl"],
    intents: ["calcular seguridad social", "aportes independientes"],
    badges: ["Actualizado 2026"],
    related: ["nomina-completa", "comparador", "retencion-salarios"],
  },
  {
    id: "ganancias-ocasionales",
    href: "/calculadoras/ganancias-ocasionales",
    title: "Ganancias Ocasionales - Inmuebles",
    description: "Calcula impuesto por venta de activos fijos con ajuste fiscal.",
    iconName: "TrendingUp",
    articles: ["299", "300", "314"],
    category: "patrimonio",
    tags: ["ganancia ocasional", "inmuebles", "venta"],
    intents: ["impuesto venta inmueble", "ganancia ocasional inmueble"],
    badges: ["Actualizado 2026"],
    related: ["ganancias-loterias", "herencias", "renta"],
  },
  {
    id: "herencias",
    href: "/calculadoras/herencias",
    title: "Herencias y Donaciones",
    description: "Impuesto sobre herencias, legados y donaciones con exenciones.",
    iconName: "Gift",
    articles: ["302", "307", "314"],
    category: "patrimonio",
    tags: ["herencias", "donaciones", "legados"],
    intents: ["impuesto herencia", "calcular donacion"],
    badges: ["Actualizado 2026"],
    related: ["ganancias-ocasionales", "patrimonio"],
  },
  {
    id: "dividendos",
    href: "/calculadoras/dividendos",
    title: "Dividendos Personas Naturales",
    description: "Impuesto sobre dividendos gravados y no gravados.",
    iconName: "PieChart",
    articles: ["242", "49"],
    category: "renta",
    tags: ["dividendos", "acciones", "retencion"],
    intents: ["impuesto dividendos", "retencion dividendos"],
    badges: ["Actualizado 2026"],
    related: ["dividendos-juridicas", "renta"],
  },
  {
    id: "patrimonio",
    href: "/calculadoras/patrimonio",
    title: "Impuesto al Patrimonio",
    description: "Impuesto progresivo sobre patrimonio liquido 2026.",
    iconName: "Building2",
    articles: ["292-2", "296-3"],
    category: "patrimonio",
    tags: ["patrimonio", "impuesto patrimonio", "riqueza"],
    intents: ["calcular impuesto al patrimonio", "patrimonio liquido"],
    badges: ["Actualizado 2026", "Incluye reforma"],
    related: ["comparacion-patrimonial", "renta"],
  },
  {
    id: "renta-juridicas",
    href: "/calculadoras/renta-juridicas",
    title: "Renta Personas Juridicas",
    description: "Impuesto corporativo con tarifas sectoriales y sobretasa financiero.",
    iconName: "Building",
    articles: ["240", "240-1"],
    category: "renta",
    tags: ["renta juridicas", "impuesto corporativo"],
    intents: ["impuesto renta empresa", "renta sociedad"],
    badges: ["Actualizado 2026"],
    related: ["simple", "zonas-francas", "descuentos-tributarios"],
  },
  {
    id: "sanciones-ampliadas",
    href: "/calculadoras/sanciones-ampliadas",
    title: "Sanciones Tributarias",
    description: "No declarar, correccion e inexactitud con reduccion Art. 640.",
    iconName: "Gavel",
    articles: ["643", "644", "647"],
    category: "sanciones",
    tags: ["sanciones", "no declarar", "inexactitud"],
    intents: ["sancion no declarar", "sancion correccion"],
    badges: ["Actualizado 2026"],
    related: ["sanciones", "intereses-mora"],
  },
  {
    id: "debo-declarar",
    href: "/calculadoras/debo-declarar",
    title: "Debo Declarar Renta",
    description: "Verifica obligacion de declarar comparando topes en UVT.",
    iconName: "CheckCircle",
    articles: ["592", "593"],
    category: "renta",
    tags: ["debo declarar", "obligado", "topes", "renta"],
    intents: ["debo declarar renta", "estoy obligado a declarar"],
    badges: ["Actualizado 2026"],
    related: ["renta", "retencion", "anticipo"],
    isTop5: true,
  },
  {
    id: "anticipo",
    href: "/calculadoras/anticipo",
    title: "Anticipo de Renta",
    description: "Calcula anticipo del impuesto de renta para el siguiente periodo.",
    iconName: "FastForward",
    articles: ["807"],
    category: "renta",
    tags: ["anticipo", "renta", "periodo siguiente"],
    intents: ["calcular anticipo renta"],
    badges: ["Actualizado 2026"],
    related: ["renta", "debo-declarar"],
  },
  {
    id: "timbre",
    href: "/calculadoras/timbre",
    title: "Impuesto de Timbre",
    description: "Impuesto 1% sobre documentos que superen 6,000 UVT.",
    iconName: "Stamp",
    articles: ["519", "520"],
    category: "otros",
    tags: ["timbre", "documentos"],
    intents: ["impuesto de timbre", "timbre 1%"],
    badges: ["Actualizado 2026", "Incluye reforma"],
    related: ["renta-juridicas"],
  },
  {
    id: "liquidacion-laboral",
    href: "/calculadoras/liquidacion-laboral",
    title: "Liquidacion de Contrato Laboral",
    description: "Cesantias, intereses, prima, vacaciones e indemnizacion.",
    iconName: "FileText",
    articles: [],
    category: "laboral",
    tags: ["liquidacion", "contrato", "indemnizacion"],
    intents: ["liquidar contrato", "liquidacion laboral"],
    badges: ["Actualizado 2026"],
    related: ["nomina-completa", "horas-extras"],
  },
  {
    id: "horas-extras",
    href: "/calculadoras/horas-extras",
    title: "Horas Extras y Recargos",
    description: "Calcula extras diurnas, nocturnas y dominicales.",
    iconName: "Clock",
    articles: [],
    category: "laboral",
    tags: ["horas extras", "recargos", "dominical"],
    intents: ["calcular horas extras", "recargo nocturno"],
    badges: ["Actualizado 2026", "Incluye reforma"],
    related: ["nomina-completa", "liquidacion-laboral"],
  },
  {
    id: "retencion-salarios",
    href: "/calculadoras/retencion-salarios",
    title: "Retencion Salarios Proc. 1",
    description: "Retencion mensual con depuracion completa Art. 388.",
    iconName: "Calculator",
    articles: ["383", "388"],
    category: "laboral",
    tags: ["retencion salarios", "proc 1", "depuracion"],
    intents: ["retencion salarios procedimiento 1", "depuracion art 388"],
    badges: ["Actualizado 2026"],
    related: ["retencion", "renta", "nomina-completa"],
  },
  {
    id: "intereses-mora",
    href: "/calculadoras/intereses-mora",
    title: "Intereses Moratorios DIAN",
    description: "Calcula intereses de mora sobre deudas tributarias.",
    iconName: "Percent",
    articles: ["634", "635"],
    category: "sanciones",
    tags: ["intereses", "mora", "dian"],
    intents: ["intereses de mora", "mora dian"],
    badges: ["Actualizado 2026"],
    related: ["sanciones", "sanciones-ampliadas"],
  },
  {
    id: "simple",
    href: "/calculadoras/simple",
    title: "Regimen SIMPLE (RST)",
    description: "Impuesto unificado SIMPLE por grupo de actividad.",
    iconName: "Layers",
    articles: ["903", "908"],
    category: "renta",
    tags: ["simple", "rst", "regimen"],
    intents: ["calcular simple", "regimen simple"],
    badges: ["Actualizado 2026"],
    related: ["comparador-regimenes", "renta-juridicas"],
  },
  {
    id: "beneficio-auditoria",
    href: "/calculadoras/beneficio-auditoria",
    title: "Beneficio de Auditoria",
    description: "Verifica si aplica reduccion del periodo de firmeza.",
    iconName: "Search",
    articles: ["689-3"],
    category: "renta",
    tags: ["beneficio auditoria", "firmeza"],
    intents: ["beneficio de auditoria", "firmeza declaracion"],
    badges: ["Actualizado 2026"],
    related: ["renta", "anticipo"],
  },
  {
    id: "pension",
    href: "/calculadoras/pension",
    title: "Verificador de Pension",
    description: "Verifica edad y semanas cotizadas.",
    iconName: "Wallet",
    articles: [],
    category: "laboral",
    tags: ["pension", "semanas", "edad"],
    intents: ["me puedo pensionar", "semanas pension"],
    badges: ["Actualizado 2026", "Incluye reforma"],
    related: ["seguridad-social", "nomina-completa"],
  },
  {
    id: "depreciacion",
    href: "/calculadoras/depreciacion",
    title: "Depreciacion Fiscal",
    description: "Deduccion anual por depreciacion de activos fijos.",
    iconName: "TrendingDown",
    articles: ["128", "137"],
    category: "otros",
    tags: ["depreciacion", "activos", "fiscal"],
    intents: ["depreciacion fiscal", "vida util activo"],
    badges: ["Actualizado 2026"],
    related: ["renta-juridicas"],
  },
  {
    id: "consumo",
    href: "/calculadoras/consumo",
    title: "Impuesto al Consumo",
    description: "Impuesto nacional al consumo para restaurantes y otros.",
    iconName: "Coffee",
    articles: ["512-1"],
    category: "iva",
    tags: ["consumo", "inc", "restaurantes"],
    intents: ["impuesto al consumo", "inc"],
    badges: ["Actualizado 2026"],
    related: ["iva"],
  },
  {
    id: "ica",
    href: "/calculadoras/ica",
    title: "Impuesto ICA",
    description: "Calcula ICA con formulario de 38 renglones y sobretasas.",
    iconName: "MapPin",
    articles: [],
    category: "otros",
    tags: ["ica", "industria y comercio", "municipal"],
    intents: ["calcular ica", "impuesto municipal"],
    badges: ["Actualizado 2026"],
    related: ["simple", "renta-juridicas"],
  },
  {
    id: "ganancias-loterias",
    href: "/calculadoras/ganancias-loterias",
    title: "Ganancias Ocasionales - Loterias",
    description: "Impuesto 20% sobre premios de loterias, rifas y apuestas.",
    iconName: "Ticket",
    articles: ["304", "317"],
    category: "otros",
    tags: ["loteria", "premios", "ganancia ocasional"],
    intents: ["impuesto loteria", "premio loteria"],
    badges: ["Actualizado 2026"],
    related: ["retencion", "ganancias-ocasionales"],
  },
  {
    id: "dividendos-juridicas",
    href: "/calculadoras/dividendos-juridicas",
    title: "Dividendos Personas Juridicas",
    description: "Tarifas para nacionales y extranjeros (Art. 242-1 ET).",
    iconName: "Briefcase",
    articles: ["242-1", "245"],
    category: "renta",
    tags: ["dividendos juridicas", "retencion"],
    intents: ["impuesto dividendos juridicas"],
    badges: ["Actualizado 2026"],
    related: ["dividendos", "renta-juridicas"],
  },
  {
    id: "descuentos-tributarios",
    href: "/calculadoras/descuentos-tributarios",
    title: "Descuentos Tributarios",
    description: "IVA activos productivos, donaciones e impuesto exterior.",
    iconName: "BadgePercent",
    articles: ["254", "257", "258-1"],
    category: "renta",
    tags: ["descuentos", "donaciones", "impuesto exterior"],
    intents: ["descuentos tributarios", "descuento impuesto"],
    badges: ["Actualizado 2026"],
    related: ["renta-juridicas"],
  },
  {
    id: "zonas-francas",
    href: "/calculadoras/zonas-francas",
    title: "Zonas Francas",
    description: "Tarifa preferencial del 20% con plan de exportaciones.",
    iconName: "Factory",
    articles: ["240-1"],
    category: "renta",
    tags: ["zonas francas", "tarifa 20"],
    intents: ["impuesto zona franca", "tarifa zonas francas"],
    badges: ["Actualizado 2026"],
    related: ["renta-juridicas"],
  },
  {
    id: "comparacion-patrimonial",
    href: "/calculadoras/comparacion-patrimonial",
    title: "Comparacion Patrimonial",
    description: "Detecta renta no justificada por incremento patrimonial.",
    iconName: "GitCompare",
    articles: ["236", "239"],
    category: "patrimonio",
    tags: ["comparacion patrimonial", "incremento patrimonial"],
    intents: ["incremento patrimonial", "renta no justificada"],
    badges: ["Actualizado 2026"],
    related: ["patrimonio", "renta"],
  },
  {
    id: "comparador-regimenes",
    href: "/calculadoras/comparador-regimenes",
    title: "Comparador Ordinario vs SIMPLE",
    description: "Comparacion lado a lado de carga tributaria total.",
    iconName: "Columns",
    articles: ["241", "908"],
    category: "renta",
    tags: ["comparador regimenes", "simple", "ordinario"],
    intents: ["simple vs ordinario", "comparar regimen"],
    badges: ["Actualizado 2026"],
    related: ["simple", "renta-juridicas"],
  },
  {
    id: "nomina-completa",
    href: "/calculadoras/nomina-completa",
    title: "Nomina Completa",
    description: "Desglose de prestaciones, seguridad social y parafiscales.",
    iconName: "ClipboardList",
    articles: ["204"],
    category: "laboral",
    tags: ["nomina", "prestaciones", "parafiscales", "costos"],
    intents: ["calcular nomina", "costo de un empleado", "prestaciones sociales"],
    badges: ["Actualizado 2026", "Incluye reforma"],
    related: ["comparador", "seguridad-social", "liquidacion-laboral"],
    isTop5: true,
  },
  {
    id: "licencia-maternidad",
    href: "/calculadoras/licencia-maternidad",
    title: "Licencia Maternidad y Paternidad",
    description: "Duracion y valor con leyes vigentes.",
    iconName: "Baby",
    articles: [],
    category: "laboral",
    tags: ["licencia", "maternidad", "paternidad"],
    intents: ["calcular licencia maternidad", "licencia paternidad"],
    badges: ["Actualizado 2026", "Incluye reforma"],
    related: ["nomina-completa", "seguridad-social"],
  },
];

export const CALCULATORS_BY_ID = Object.fromEntries(
  CALCULATORS_CATALOG.map((item) => [item.id, item]),
) as Record<string, CalculatorCatalogItem>;

export const TOP5_CALCULATORS = CALCULATORS_CATALOG.filter((item) => item.isTop5);
