// ── Novedades Normativas ──
// Cambios recientes en la legislacion tributaria colombiana

export interface NovedadNormativa {
  id: string;
  fecha: string; // ISO date YYYY-MM-DD
  titulo: string;
  resumen: string;
  tipo: "ley" | "decreto" | "resolucion" | "circular" | "sentencia" | "concepto";
  fuente: string;
  numero: string;
  impacto: "alto" | "medio" | "bajo";
  articulosET?: string[];
  tags: string[];
}

export const NOVEDADES: NovedadNormativa[] = [
  // ── 2026 ──
  {
    id: "nov-001",
    fecha: "2026-01-15",
    titulo: "Resolucion DIAN fija calendario tributario 2026",
    resumen: "La DIAN expide la resolucion con los plazos para declarar y pagar las obligaciones tributarias del ano gravable 2025. Se establecen fechas para renta, IVA, retencion en la fuente, SIMPLE, patrimonio y demas impuestos nacionales.",
    tipo: "resolucion",
    fuente: "DIAN",
    numero: "000012 de 2026",
    impacto: "alto",
    articulosET: ["574", "579", "580", "811"],
    tags: ["calendario tributario", "plazos", "vencimientos", "2026"],
  },
  {
    id: "nov-002",
    fecha: "2026-01-10",
    titulo: "Resolucion DIAN fija valor de la UVT para 2026",
    resumen: "La DIAN fija el valor de la Unidad de Valor Tributario (UVT) en $49.799 para el ano 2026, con base en la variacion del IPC certificada por el DANE. Este valor actualiza umbrales, tarifas, deducciones y sanciones del Estatuto Tributario.",
    tipo: "resolucion",
    fuente: "DIAN",
    numero: "000005 de 2026",
    impacto: "alto",
    articulosET: ["868"],
    tags: ["UVT", "unidad de valor tributario", "actualizacion", "2026"],
  },
  {
    id: "nov-003",
    fecha: "2026-01-03",
    titulo: "Decreto fija salario minimo 2026 en $1.750.905",
    resumen: "El Gobierno Nacional fija el salario minimo mensual legal vigente (SMLMV) para 2026 en $1.750.905 y el auxilio de transporte en $249.095. Estos valores impactan bases de retencion, aportes a seguridad social y el calculo de diversas obligaciones tributarias.",
    tipo: "decreto",
    fuente: "Ministerio del Trabajo",
    numero: "0025 de 2026",
    impacto: "alto",
    tags: ["salario minimo", "SMLMV", "auxilio de transporte", "2026"],
  },

  // ── 2025 ──
  {
    id: "nov-004",
    fecha: "2025-12-28",
    titulo: "Decreto reglamentario de la reforma tributaria Ley 2277",
    resumen: "Se expide decreto reglamentario que ajusta procedimientos de retencion en la fuente, limites de deducciones y requisitos para el regimen SIMPLE, en desarrollo de la Ley 2277 de 2022.",
    tipo: "decreto",
    fuente: "MinHacienda",
    numero: "1474 de 2025",
    impacto: "alto",
    articulosET: ["383", "387", "388", "401", "903"],
    tags: ["reglamentario", "reforma tributaria", "retencion", "SIMPLE"],
  },
  {
    id: "nov-005",
    fecha: "2025-11-15",
    titulo: "Resolucion DIAN sobre facturacion electronica de venta",
    resumen: "La DIAN actualiza los requisitos tecnicos y de validacion para la factura electronica de venta, documento soporte en operaciones con no obligados y notas de ajuste, con plazo de implementacion hasta marzo 2026.",
    tipo: "resolucion",
    fuente: "DIAN",
    numero: "000165 de 2025",
    impacto: "medio",
    articulosET: ["615", "616-1", "617"],
    tags: ["factura electronica", "documento soporte", "validacion previa"],
  },
  {
    id: "nov-006",
    fecha: "2025-10-20",
    titulo: "Circular DIAN sobre tratamiento de criptoactivos",
    resumen: "La DIAN emite circular con lineamientos sobre la declaracion de criptoactivos como activos en la declaracion de renta, su valoracion y el tratamiento de ganancias realizadas.",
    tipo: "circular",
    fuente: "DIAN",
    numero: "015 de 2025",
    impacto: "medio",
    articulosET: ["261", "267", "300"],
    tags: ["criptoactivos", "activos virtuales", "declaracion de renta"],
  },
  {
    id: "nov-007",
    fecha: "2025-09-12",
    titulo: "Sentencia Corte Constitucional sobre impuesto al patrimonio",
    resumen: "La Corte Constitucional declara exequible el impuesto al patrimonio establecido en la Ley 2277 de 2022, rechazando demandas por presunta violacion al principio de no confiscatoriedad. Se confirman las tarifas progresivas del 0,5% al 1,5%.",
    tipo: "sentencia",
    fuente: "Corte Constitucional",
    numero: "C-389 de 2025",
    impacto: "alto",
    articulosET: ["292-3", "294-3", "295-3", "296-3"],
    tags: ["patrimonio", "constitucionalidad", "tarifas", "no confiscatoriedad"],
  },
  {
    id: "nov-008",
    fecha: "2025-08-05",
    titulo: "Concepto DIAN sobre renta de plataformas digitales",
    resumen: "La DIAN emite concepto general sobre el tratamiento tributario de ingresos obtenidos a traves de plataformas digitales de economia colaborativa, incluyendo aplicaciones de transporte y entregas.",
    tipo: "concepto",
    fuente: "DIAN",
    numero: "0758 de 2025",
    impacto: "medio",
    articulosET: ["24", "408", "437-2"],
    tags: ["economia digital", "plataformas", "retencion", "IVA"],
  },
  {
    id: "nov-009",
    fecha: "2025-06-30",
    titulo: "Decreto sobre precios de transferencia 2025",
    resumen: "Se reglamentan los plazos y condiciones para la presentacion de la documentacion comprobatoria, declaracion informativa y el informe pais por pais en materia de precios de transferencia para el ano gravable 2024.",
    tipo: "decreto",
    fuente: "MinHacienda",
    numero: "0892 de 2025",
    impacto: "medio",
    articulosET: ["260-1", "260-2", "260-4", "260-5", "260-9"],
    tags: ["precios de transferencia", "vinculados economicos", "informe pais por pais"],
  },
  {
    id: "nov-010",
    fecha: "2025-04-15",
    titulo: "Resolucion DIAN implementa sistema de devolucion automatica",
    resumen: "La DIAN implementa un sistema automatizado para la devolucion y compensacion de saldos a favor en IVA y renta, reduciendo los tiempos de tramite a 15 dias habiles para contribuyentes que cumplan requisitos especificos.",
    tipo: "resolucion",
    fuente: "DIAN",
    numero: "000089 de 2025",
    impacto: "medio",
    articulosET: ["815", "816", "850", "854", "855"],
    tags: ["devoluciones", "saldos a favor", "compensacion", "IVA", "renta"],
  },

  // ── 2024 ──
  {
    id: "nov-011",
    fecha: "2024-12-18",
    titulo: "Ley 2365 de 2024 - Licencia de paternidad",
    resumen: "Se amplian las licencias de paternidad y se establecen incentivos tributarios para empleadores que superen los periodos minimos. Modifica tratamiento de deducciones por pagos laborales.",
    tipo: "ley",
    fuente: "Congreso de la Republica",
    numero: "2365 de 2024",
    impacto: "bajo",
    articulosET: ["108", "387"],
    tags: ["licencia paternidad", "deducciones laborales", "incentivos"],
  },
  {
    id: "nov-012",
    fecha: "2024-10-25",
    titulo: "Decreto reglamentario del Regimen SIMPLE de Tributacion",
    resumen: "Se reglamentan aspectos del Regimen SIMPLE de Tributacion incluyendo la actualizacion de tarifas consolidadas, creditos tributarios por aportes a pension y requisitos de permanencia.",
    tipo: "decreto",
    fuente: "MinHacienda",
    numero: "1563 de 2024",
    impacto: "medio",
    articulosET: ["903", "904", "905", "906", "907", "908", "910", "911"],
    tags: ["SIMPLE", "regimen simple", "tarifas", "creditos tributarios"],
  },
  {
    id: "nov-013",
    fecha: "2024-09-08",
    titulo: "Sentencia sobre beneficios de convenios de doble imposicion",
    resumen: "El Consejo de Estado aclara el alcance de los beneficios del Convenio para Evitar la Doble Imposicion (CDI) con Espana, especialmente en materia de dividendos, intereses y regalias.",
    tipo: "sentencia",
    fuente: "Consejo de Estado",
    numero: "25892 de 2024",
    impacto: "medio",
    articulosET: ["18-1", "20-1", "245", "254"],
    tags: ["convenios", "doble imposicion", "CDI", "Espana", "dividendos"],
  },
  {
    id: "nov-014",
    fecha: "2024-07-20",
    titulo: "Circular DIAN sobre nomina electronica",
    resumen: "La DIAN emite lineamientos adicionales sobre la implementacion del documento soporte de pago de nomina electronica (DSPNE), incluyendo notas de ajuste y plazos para transmision.",
    tipo: "circular",
    fuente: "DIAN",
    numero: "008 de 2024",
    impacto: "medio",
    articulosET: ["107", "108", "383"],
    tags: ["nomina electronica", "DSPNE", "documento soporte", "deduccion"],
  },
  {
    id: "nov-015",
    fecha: "2024-05-03",
    titulo: "Resolucion sobre habilitacion de facturador electronico",
    resumen: "La DIAN establece nuevos requisitos para la habilitacion como facturador electronico y actualiza el procedimiento de validacion previa, incluyendo requisitos de firma digital y envio al adquirente.",
    tipo: "resolucion",
    fuente: "DIAN",
    numero: "000042 de 2024",
    impacto: "bajo",
    articulosET: ["615", "616-1", "617", "618"],
    tags: ["facturacion electronica", "habilitacion", "validacion previa"],
  },

  // ── 2023 ──
  {
    id: "nov-016",
    fecha: "2023-12-22",
    titulo: "Decreto de plazos tributarios 2024",
    resumen: "El Gobierno expide el decreto con los plazos para el cumplimiento de obligaciones tributarias del ano gravable 2023, incluyendo renta, IVA, retencion, patrimonio, SIMPLE y obligaciones informativas.",
    tipo: "decreto",
    fuente: "MinHacienda",
    numero: "2229 de 2023",
    impacto: "alto",
    articulosET: ["574", "579", "580", "811"],
    tags: ["plazos", "calendario tributario", "vencimientos", "2024"],
  },
  {
    id: "nov-017",
    fecha: "2023-08-15",
    titulo: "Concepto DIAN sobre residencia fiscal en teletrabajo internacional",
    resumen: "La DIAN emite concepto aclarando los criterios para determinar la residencia fiscal de personas que realizan teletrabajo desde Colombia para empleadores del exterior, incluyendo el conteo de dias de permanencia.",
    tipo: "concepto",
    fuente: "DIAN",
    numero: "0421 de 2023",
    impacto: "medio",
    articulosET: ["10", "9", "24"],
    tags: ["residencia fiscal", "teletrabajo", "no residentes", "permanencia"],
  },
  {
    id: "nov-018",
    fecha: "2023-06-10",
    titulo: "Sentencia Corte Constitucional sobre regalias de software",
    resumen: "La Corte se pronuncia sobre el tratamiento tributario de las regalias por licenciamiento de software, distinguiendo entre regalias y servicios tecnicos para efectos de retencion en la fuente.",
    tipo: "sentencia",
    fuente: "Corte Constitucional",
    numero: "C-256 de 2023",
    impacto: "bajo",
    articulosET: ["24", "406", "408", "411"],
    tags: ["software", "regalias", "servicios tecnicos", "retencion"],
  },

  // ── 2022 ──
  {
    id: "nov-019",
    fecha: "2022-12-13",
    titulo: "Ley 2277 de 2022 - Reforma Tributaria para la Igualdad",
    resumen: "Se aprueba la reforma tributaria mas significativa del gobierno Petro. Incluye: aumento de tarifa de renta para patrimonios altos, impuesto a ganancias ocasionales al 15%, limitacion de beneficios tributarios, impuesto a bebidas azucaradas y alimentos ultraprocesados, cambios en regimen SIMPLE, y ajustes al impuesto al patrimonio.",
    tipo: "ley",
    fuente: "Congreso de la Republica",
    numero: "2277 de 2022",
    impacto: "alto",
    articulosET: ["241", "242", "245", "292-3", "295-3", "303-1", "383", "388", "903", "904", "905", "906", "907", "908"],
    tags: ["reforma tributaria", "renta", "patrimonio", "ganancias ocasionales", "SIMPLE", "bebidas azucaradas"],
  },
  {
    id: "nov-020",
    fecha: "2022-11-30",
    titulo: "Circular DIAN sobre impuesto saludable a ultraprocesados",
    resumen: "La DIAN emite circular con los lineamientos para la aplicacion gradual del impuesto saludable a bebidas azucaradas y alimentos ultraprocesados a partir de noviembre de 2023.",
    tipo: "circular",
    fuente: "DIAN",
    numero: "022 de 2022",
    impacto: "medio",
    tags: ["impuesto saludable", "bebidas azucaradas", "ultraprocesados"],
  },

  // ── 2021 ──
  {
    id: "nov-021",
    fecha: "2021-09-14",
    titulo: "Ley 2155 de 2021 - Ley de Inversion Social",
    resumen: "Se aprueba la ley de inversion social que establece la tarifa general de renta para personas juridicas en 35%, crea el impuesto de normalizacion tributaria, modifica el regimen SIMPLE e implementa el programa de ingreso solidario.",
    tipo: "ley",
    fuente: "Congreso de la Republica",
    numero: "2155 de 2021",
    impacto: "alto",
    articulosET: ["240", "241", "903", "905", "908"],
    tags: ["inversion social", "renta", "normalizacion", "SIMPLE", "tarifa"],
  },
  {
    id: "nov-022",
    fecha: "2021-07-28",
    titulo: "Ley 2114 de 2021 - Licencia parental compartida",
    resumen: "Se establece la licencia parental compartida y la licencia parental flexible de tiempo parcial. Impacta las deducciones laborales y los calculos de retencion en la fuente por pagos laborales.",
    tipo: "ley",
    fuente: "Congreso de la Republica",
    numero: "2114 de 2021",
    impacto: "bajo",
    articulosET: ["108", "387"],
    tags: ["licencia parental", "deducciones laborales", "retencion"],
  },

  // ── 2019-2020 ──
  {
    id: "nov-023",
    fecha: "2019-12-27",
    titulo: "Ley 2010 de 2019 - Ley de Crecimiento Economico",
    resumen: "Se aprueba la ley de crecimiento economico que reduce la tarifa de renta a personas juridicas gradualmente, establece reglas sobre descuento del ICA en renta, modifica retenciones a dividendos y crea el regimen SIMPLE modernizado.",
    tipo: "ley",
    fuente: "Congreso de la Republica",
    numero: "2010 de 2019",
    impacto: "alto",
    articulosET: ["115", "240", "242", "242-1", "903", "904", "905", "906", "907", "908", "910", "911", "912"],
    tags: ["crecimiento economico", "tarifa renta", "ICA", "dividendos", "SIMPLE"],
  },
  {
    id: "nov-024",
    fecha: "2020-06-01",
    titulo: "Decreto legislativo sobre plazos tributarios por COVID-19",
    resumen: "En el marco de la emergencia sanitaria, el Gobierno modifica los plazos para la presentacion de declaraciones tributarias y facilita el pago diferido de obligaciones. Se establecen beneficios temporales para sectores afectados.",
    tipo: "decreto",
    fuente: "MinHacienda",
    numero: "655 de 2020",
    impacto: "alto",
    articulosET: ["579", "580", "811", "814"],
    tags: ["COVID-19", "plazos", "emergencia sanitaria", "facilidades de pago"],
  },
  {
    id: "nov-025",
    fecha: "2025-03-20",
    titulo: "Concepto DIAN sobre retenciones en contratos de prestacion de servicios",
    resumen: "La DIAN aclara la base de retencion en la fuente aplicable a contratos de prestacion de servicios profesionales y de consultoria, diferenciando personas naturales declarantes y no declarantes de renta.",
    tipo: "concepto",
    fuente: "DIAN",
    numero: "0215 de 2025",
    impacto: "medio",
    articulosET: ["383", "392", "401"],
    tags: ["retencion", "servicios profesionales", "consultoria", "base de retencion"],
  },
  {
    id: "nov-026",
    fecha: "2024-03-10",
    titulo: "Resolucion DIAN establece grupos de implementacion de nomina electronica",
    resumen: "La DIAN establece el calendario de implementacion obligatoria del documento soporte de pago de nomina electronica para empleadores segun su numero de empleados.",
    tipo: "resolucion",
    fuente: "DIAN",
    numero: "000028 de 2024",
    impacto: "medio",
    articulosET: ["107", "108"],
    tags: ["nomina electronica", "implementacion", "empleadores"],
  },
  {
    id: "nov-027",
    fecha: "2023-04-20",
    titulo: "Decreto reglamentario del impuesto al patrimonio Ley 2277",
    resumen: "Se reglamenta el impuesto al patrimonio creado por la Ley 2277 de 2022, incluyendo la determinacion de la base gravable, exclusiones, tarifas marginales y plazos de pago.",
    tipo: "decreto",
    fuente: "MinHacienda",
    numero: "0589 de 2023",
    impacto: "alto",
    articulosET: ["292-3", "294-3", "295-3", "296-3", "297-3"],
    tags: ["patrimonio", "base gravable", "tarifas marginales", "exclusiones"],
  },
  {
    id: "nov-028",
    fecha: "2025-07-15",
    titulo: "Decreto sobre reglamentacion ICA territorial",
    resumen: "El Gobierno Nacional expide lineamientos para la armonizacion del Impuesto de Industria y Comercio (ICA) a nivel territorial, buscando simplificar el cumplimiento para contribuyentes con presencia en multiples municipios.",
    tipo: "decreto",
    fuente: "MinHacienda",
    numero: "1120 de 2025",
    impacto: "medio",
    articulosET: ["115"],
    tags: ["ICA", "industria y comercio", "territorial", "armonizacion"],
  },
];
